services:
  backend:
    environment:
      ENVIRONMENT: prod
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  
  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=false 
      - WATCHPACK_POLLING=false
    command: ["npm", "run", "build"]
    restart: "no"
  
  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"